/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteRouteImport } from './routes/_app/route'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AppPartsRouteImport } from './routes/_app/parts'
import { Route as AppModelsRouteImport } from './routes/_app/models'
import { Route as AppCategoriesRouteImport } from './routes/_app/categories'
import { Route as AppBrandsRouteImport } from './routes/_app/brands'
import { Route as authLoginRouteImport } from './routes/(auth)/login'

const AppRouteRoute = AppRouteRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppPartsRoute = AppPartsRouteImport.update({
  id: '/parts',
  path: '/parts',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppModelsRoute = AppModelsRouteImport.update({
  id: '/models',
  path: '/models',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppCategoriesRoute = AppCategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppBrandsRoute = AppBrandsRouteImport.update({
  id: '/brands',
  path: '/brands',
  getParentRoute: () => AppRouteRoute,
} as any)
const authLoginRoute = authLoginRouteImport.update({
  id: '/(auth)/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/login': typeof authLoginRoute
  '/brands': typeof AppBrandsRoute
  '/categories': typeof AppCategoriesRoute
  '/models': typeof AppModelsRoute
  '/parts': typeof AppPartsRoute
}
export interface FileRoutesByTo {
  '/login': typeof authLoginRoute
  '/brands': typeof AppBrandsRoute
  '/categories': typeof AppCategoriesRoute
  '/models': typeof AppModelsRoute
  '/parts': typeof AppPartsRoute
  '/': typeof AppIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteRouteWithChildren
  '/(auth)/login': typeof authLoginRoute
  '/_app/brands': typeof AppBrandsRoute
  '/_app/categories': typeof AppCategoriesRoute
  '/_app/models': typeof AppModelsRoute
  '/_app/parts': typeof AppPartsRoute
  '/_app/': typeof AppIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/login' | '/brands' | '/categories' | '/models' | '/parts'
  fileRoutesByTo: FileRoutesByTo
  to: '/login' | '/brands' | '/categories' | '/models' | '/parts' | '/'
  id:
    | '__root__'
    | '/_app'
    | '/(auth)/login'
    | '/_app/brands'
    | '/_app/categories'
    | '/_app/models'
    | '/_app/parts'
    | '/_app/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRouteRoute: typeof AppRouteRouteWithChildren
  authLoginRoute: typeof authLoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/parts': {
      id: '/_app/parts'
      path: '/parts'
      fullPath: '/parts'
      preLoaderRoute: typeof AppPartsRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/models': {
      id: '/_app/models'
      path: '/models'
      fullPath: '/models'
      preLoaderRoute: typeof AppModelsRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/categories': {
      id: '/_app/categories'
      path: '/categories'
      fullPath: '/categories'
      preLoaderRoute: typeof AppCategoriesRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/brands': {
      id: '/_app/brands'
      path: '/brands'
      fullPath: '/brands'
      preLoaderRoute: typeof AppBrandsRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/(auth)/login': {
      id: '/(auth)/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof authLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AppRouteRouteChildren {
  AppBrandsRoute: typeof AppBrandsRoute
  AppCategoriesRoute: typeof AppCategoriesRoute
  AppModelsRoute: typeof AppModelsRoute
  AppPartsRoute: typeof AppPartsRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppBrandsRoute: AppBrandsRoute,
  AppCategoriesRoute: AppCategoriesRoute,
  AppModelsRoute: AppModelsRoute,
  AppPartsRoute: AppPartsRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AppRouteRoute: AppRouteRouteWithChildren,
  authLoginRoute: authLoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
